export enum SCORABLE_VALUES {
  DEFINITELY_AGREE = "DEFINITELY_AGREE",
  SLIGHTLY_AGREE = "SLIGHTLY_AGREE",
  SLIGHTLY_DISAGREE = "SLIGHTLY_DISAGREE",
  DEFINITELY_DISAGREE = "DEFINITELY_DISAGREE",
}
